default.depth=99

node.minSize=20
node.defaultWidth=120
node.defaultHeight=80

port.size=10

label.defaultFontSize=14
label.defaultPadding=4
label.defaultText=New Label

rect.defaultLabel=Class
oval.defaultLabel=Use Case
rect.defaultFillColor=#FFF9C4
oval.defaultFillColor=#CDE5FF

toolbar.buttonWidth=84
toolbar.buttonHeight=44
toolbar.buttonFontSize=13

selection.boxStrokeColor=#325AB4
selection.boxFillAlpha=70

link.portRevealProximityPx=16

